### ISSUE TITLE
Youtube and Vimeo poster frames on videos coming in below res

### ISSUE THREAD

**Issue by theindexla** [theindex-la/theindex.la-www#41]
see Truen's index page: http://staging.theindex.la/artist/truen-pence/ 
(also screenshot below) 

vs. Truen's Vimeo page: https://vimeo.com/truen

![screen shot 2016-08-14 at 1 30 55 pm](https://cloud.githubusercontent.com/assets/20481365/17651847/760eacc0-6223-11e6-9b13-6b0a82279564.png)

**Comment by kitajchuk** [comment]
There's nothing we can do about the poster URL that the oembed pulls. We're showing what is scraped so if its too low res we'll have to add our own in those cases.

**Comment by theindexla** [comment]
so strange. Wondering why the images look so crisp on Vimeo. Is there
anywhere in the embed that allows you to set the size of the image? Silly
question, but worth the double check.

**Comment by kitajchuk** [comment]
Unfortunately there is not. The oembed data is scraped when you put the video url in prismic. The data that comes from that is what we are left with. Squarespace is the same way when they scrape oembed data as well.

I would also point out that on the vimeo page the images are not being displayed as a poster frame but rather as literal thumbnails. My guess is that he just doesn't have a high res poster frame uploaded because technically the field is a thumbnail field, not a poster frame field.
